header:
  license:
    spdx-id: MPL-2.0
    copyright-owner: RTE (http://www.rte-france.com)
    copyright-year: '2024'
    software-name: commons-ui

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/.*'
    - '**/*.json'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.svg'


  comment: on-failure

# If you don't want to check dependencies' license compatibility, remove the following part
dependency:
  files:
    - package.json      # If this is a npm project.
