header:
  license:
    spdx-id: MPL-2.0
    copyright-owner: RTE (http://www.rte-france.com)
    software-name: commons-ui

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/.*'
    - '**/*.json'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.svg'


  comment: on-failure
