header:
  license:
    spdx-id: MPL-2.0
    copyright-owner: RTE (http://www.rte-france.com)
    copyright-year: 2020-2024
    software-name: commons-ui
    content: |
      Copyright (c) [copyright-year], [copyright-owner]
      This Source Code Form is subject to the terms of the Mozilla Public
      License, v. 2.0. If a copy of the MPL was not distributed with this
      file, You can obtain one at http://mozilla.org/MPL/2.0/.
      
  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/.*'
    - '**/*.json'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.svg'


  comment: on-failure
