name: CI
on: [push]

jobs:
    licenses:
        name: Check licenses
        runs-on: ubuntu-latest

        steps:
          - uses: actions/setup-node@v3
          - name: Checkout sources
            uses: actions/checkout@v2
            with:
                persist-credentials: false

          - name: Check License Header
            uses: apache/skywalking-eyes/header@main      # always prefer to use a revision instead of `main`.
            with:
              mode : fix
                # log: debug # optional: set the log level. The default value is `info`.
                # config: .licenserc.yaml # optional: set the config file. The default value is `.licenserc.yaml`.
                # token: # optional: the token that license eye uses when it needs to comment on the pull request. Set to empty ("") to disable commenting on pull request. The default value is ${{ github.token }}
                # mode: # optional: Which mode License-Eye should be run in. Choices are `check` or `fix`. The default value is `check`.
          # - name: Apply Changes
          #   uses: EndBug/add-and-commit@v4
          #   env:
          #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #   with:
          #     author_name: License Bot
          #     author_email: license_bot@github.com
          #     message: 'Automatic application of license header'

          - name: Create Pull Request
            if: github.ref != 'refs/heads/main'
            uses: peter-evans/create-pull-request@v6
            with:
              commit-message: License header fix(es)
              title: Fixes by Check License Header action
              body: This is an auto-generated PR with fixes by Check License Header.
              # labels: automated pr
              branch: "license-header-check/${{ github.ref_name }}"
          
          - uses: actions/github-script@v7
            if: ${{ steps.cpr.outputs.pull-request-operation }} == 'created'
            with:
              script: |
                github.rest.pulls.createComment({
                  issue_number: `${{ steps.cpr.outputs.pull-request-number }}`,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `👋 Please add missing license headers! PR:${{ steps.cpr.outputs.pull-request-url }}`
                })
                console.log(context)

          - name: Check if fail
            if: ${{ steps.cpr.outputs.pull-request-operation }} == 'created' || ${{ steps.cpr.outputs.pull-request-operation }} == 'updated'
            run: exit 1
          
          - name: Check license dependencies
            uses: daynin/nodejs-license-checker@v0.2.0
            with:
              exclude-private-packages: true
              allow-only:  |
                MPL-2.0
                MIT
                BSD-3-Clause
                BSD-2-Clause
                0BSD
                Apache-2.0
                ISC
                Apache-Style
                CC-BY-3.0
                CC-BY-4.0
                CC0-1.0
                MIT AND CC-BY-3.0
                MIT OR CC0-1.0
                Artistic-2.0
                Python-2.0
                Unlicense
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
            - name: Checkout sources
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: FixForNodeWarnings
              run: |
                  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

            - name: Build
              run: |
                  npm install
                  npm run lint
                  npm run test
                  npm run build
