name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commons-ui
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          path: 'commons-ui'

      - name: build commons-ui-consumer
        run: |
          cd $GITHUB_WORKSPACE/commons-ui
          npm install
          npm run build

      - name: broadcast event
        uses: gridsuite/broadcast-event@master
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: commons-ui-updated