name: CI
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: FixForNodeWarnings
              run: |
                  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

            - name: Build
              run: |
                  npm install
                  npm run test
                  npm run build

            - name: Broadcast update event
              uses: gridsuite/broadcast-event@master
              with:
                  token: ${{ secrets.REPO_ACCESS_TOKEN }}
                  event-type: commons-ui-updated
