name: CI
on: [push]

jobs:
    licenses:
        name: Check licenses
        runs-on: ubuntu-latest

        steps:
          - uses: actions/setup-node@v3
          - name: Checkout sources
            uses: actions/checkout@v2
            with:
                persist-credentials: false

          - name: Check License Header
            uses: apache/skywalking-eyes/header@v0.5.0
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              token : $GITHUB_TOKEN
              mode : check
          
          - name: Check license dependencies
            uses: daynin/nodejs-license-checker@v0.2.0
            with:
              exclude-private-packages: true
              allow-only:  |
                MPL-2.0
                MIT
                BSD-3-Clause
                BSD-2-Clause
                0BSD
                Apache-2.0
                ISC
                Apache-Style
                CC-BY-3.0
                CC-BY-4.0
                CC0-1.0
                MIT AND CC-BY-3.0
                MIT OR CC0-1.0
                Artistic-2.0
                Python-2.0
                Unlicense
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
            - name: Checkout sources
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: FixForNodeWarnings
              run: |
                  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

            - name: Build
              run: |
                  npm install
                  npm run lint
                  npm run test
                  npm run build
