name: CI
on: [push]

jobs:
    licenses:
        name: Check licenses
        runs-on: ubuntu-latest

        steps:
          - uses: actions/setup-node@v3
          - name: Checkout sources
            uses: actions/checkout@v2
            with:
                persist-credentials: false

          - name: Check License Header
            uses: apache/skywalking-eyes/header@v0.5.0
            with:
              mode : fix

          - name: Get current Pull Request number
            uses: actions/github-script@v7
            id: get_issue_number
            with:
              script: |
                if (context.issue.number) {
                  // Return issue number if present
                  return context.issue.number;
                } else {
                  // Otherwise return issue number from commit
                  return (
                    await github.rest.repos.listPullRequestsAssociatedWithCommit({
                      commit_sha: context.sha,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                    })
                  ).data[0].number;
                }
              result-encoding: string

          - name: Create Pull Request if necessary
            uses: peter-evans/create-pull-request@v6
            id: cpr
            if: github.ref != 'refs/heads/main' && ${{ steps.get_issue_number.outputs.result }} != ''
            with:
              commit-message: License header fix(es)
              title: Fixes by Check License Header action
              body: This is an auto-generated PR with fixes by Check License Header.
              branch: "license-header-check/${{ github.ref_name }}"
          
          - name: Comment original Pull Request
            uses: actions/github-script@v7
            if: github.ref != 'refs/heads/main' && ${{ steps.cpr.outputs.pull-request-operation }} == 'created'
            with:
              script: |
                github.rest.issues.createComment({
                  issue_number: ${{ steps.get_issue_number.outputs.result }},
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `:warning: 👋 © Please add missing license headers! PR : ${{ steps.cpr.outputs.pull-request-url }}`
                })

          # Because fix mode doesn't fail, must rerun in check mode to fail CI if necessary
          - name: Check License Header
            uses: apache/skywalking-eyes/header@v0.5.0
            with:
              mode : check
          
          - name: Check license dependencies
            uses: daynin/nodejs-license-checker@v0.2.0
            with:
              exclude-private-packages: true
              allow-only:  |
                MPL-2.0
                MIT
                BSD-3-Clause
                BSD-2-Clause
                0BSD
                Apache-2.0
                ISC
                Apache-Style
                CC-BY-3.0
                CC-BY-4.0
                CC0-1.0
                MIT AND CC-BY-3.0
                MIT OR CC0-1.0
                Artistic-2.0
                Python-2.0
                Unlicense
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
            - name: Checkout sources
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: FixForNodeWarnings
              run: |
                  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

            - name: Build
              run: |
                  npm install
                  npm run lint
                  npm run test
                  npm run build
