name: CI
on: [push]

jobs:
    licenses:
        name: Check licenses
        runs-on: ubuntu-latest

        steps:
          - uses: actions/setup-node@v3
          - name: Checkout sources
            uses: actions/checkout@v2
            with:
                persist-credentials: false

          - name: Check License Header (Check Mode)
            uses: apache/skywalking-eyes/header@v0.5.0
          
          - name: Read License WhiteList
            id: get_license_white_list
            run: echo "white_list=$(cat license_white_list.txt)" >> "$GITHUB_OUTPUT"
          
          - name: Check License Dependencies
            run: |
              npm install
              npm run licenses-check -- --onlyAllow "${{ steps.get_license_white_list.outputs.white_list }}" --excludePackages "@mapbox/jsonlint-lines-primitives@2.0.2;cartocolor@4.0.2"

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
            - name: Checkout sources
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: FixForNodeWarnings
              run: |
                  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

            - name: Build
              run: |
                  npm install
                  npm run lint
                  npm run test
                  npm run build
